language: node_js
node_js:
  - "stable"

# Cache dependencies for faster builds
cache:
  yarn: true
  directories:
    - node_modules

# Set up environment variables and disable progress bar to reduce log size
before_install:
  - npm config set progress false
  - npm install -g yarn

# Install dependencies
install:
  - yarn install

# Run build and tests
script:
  - yarn build
  - yarn test

# Notifications (optional): send a message to your email or Slack on build success/failure
notifications:
  email:
    on_success: never
    on_failure: always
